export const educationData = [
  {
    job: "Preparatory Education",
    jobDesc: "Fedrick School",
    time: "Jan 1997 - Mar 2000",
    desc: "I completed my preparatory education from this prestigious institution. I successful completed all the credits without any fallout and got A grade overall.",
    keywords: "p",
    flip: "",
    more: "block",
  },
  {
    job: "High School",
    jobDesc: "RedStreet College",
    time: "Jan 2000 - Mar 2005",
    desc: "I completed my high school degree from this prestigious institution. I successful completed all the credits without any fallout and got A grade overall.",
    keywords: "g",
    flip: "education-flip",
  },
  {
    job: "Computer Science",
    jobDesc: "Down Street College",
    time: "Jan 2006 - Mar 2008",
    desc: "I completed my computer science degree from this prestigious institution. I successful completed all the credits without any fallout and got A grade overall.",
    keywords: "c",
    flip: "",
  },
  {
    job: "Software Engineering",
    jobDesc: "Oxford University",
    time: "Jan 2009 - Mar 2010",
    desc: "I completed this degree from this prestigious institution. I successful completed all the credits without any fallout and got A grade overall.",
    icon: "fa-solid fa-graduation-cap",
    flip: "education-flip",
  },
  {
    job: "UI/UX Workshop",
    jobDesc: "IT Next Academy",
    time: "Jan 2010 - Mar 2011",
    desc: "I completed this course from this prestigious institution. I successful completed all the credits without any fallout and got A grade overall.",
    keywords: "u",
    flip: "",
    more: "block",
  },
  {
    job: "Web Development",
    jobDesc: "Lipro University",
    time: "Jan 2011 - Mar 2012",
    desc: "I completed this course from this prestigious institution. I successful completed all the credits without any fallout and got A grade overall.",
    icon: "fa-solid fa-earth-americas",
    flip: "education-flip",
    more: "block",
  },
];
export const experienceData = [
  {
    job: "Designer",
    jobDesc: "RulerSoft",
    time: "Jan 2010 - Mar 2012",
    desc: "I started my designing carrier here, spent tow years learning and working in various designing aspects.",
    keywords: "d",
    flip: "",
    more: "block",
  },
  {
    job: "Frontend Developer",
    jobDesc: "Micro IT",
    time: "Jan 2010 - Mar 2012",
    desc: "I started my frontend carrier here, spent tow years learning and working in various frontend aspects. I worked on about 40+ projects local and online.",
    keywords: "d",
    flip: "education-flip",
  },
  {
    job: "Designer",
    jobDesc: "RulerSoft",
    time: "Jan 2010 - Mar 2012",
    desc: "I started my expertise carrier here, spent tow years learning and working in various UX/UI aspects. I worked on about 70+ projects local and online.",
    keywords: "d",
    flip: "",
  },
  {
    job: "Designer",
    jobDesc: "RulerSoft",
    time: "Jan 2010 - Mar 2012",
    desc: "I recently joined here, currently working on various development aspects. I already worked on about.",
    keywords: "d",
    flip: "education-flip",
    more: "block",
  },
];
